In [1]:
import numpy as np

In [2]:
dummy_A = np.array([[1,2],[3,4]])
dimension = dummy_A.shape
print(dimension)
np.zeros([2,2])

(2, 2)


array([[0., 0.],
       [0., 0.]])

In [3]:
i = 0
arr = np.zeros((3,4,2))
print(arr)

[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]


In [4]:
i = 1
arr = np.ones((3,4,2))
print(arr)

[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]


In [5]:
# arr dimen: 2,4,5 each value should be 5
arr_5 = np.array([])
for i in range(40):
    arr_5 = np.append(arr_5,5)
arr_5.reshape(2,4,5)

array([[[5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.]],

       [[5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.]]])

In [6]:
arr_5new =np.ones((2,4,5))*5
arr_5new

array([[[5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.]],

       [[5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.]]])

In [7]:
# arange func
start = 10
stop = 30
jump = 3
val = np.arange(start,stop,jump)
print(val.reshape(1,7))
print(val.reshape(7,1))

[[10 13 16 19 22 25 28]]
[[10]
 [13]
 [16]
 [19]
 [22]
 [25]
 [28]]


In [8]:
X = np.full((2,4,5),5)
X

array([[[5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5]],

       [[5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5]]])

In [9]:
y = np.random.random((2,3,4))
#print(dimension)
z = y*10+10
z.reshape(12,2)

array([[15.45989608, 15.67665242],
       [17.72543802, 13.79444201],
       [15.25416777, 14.91651212],
       [15.5021184 , 19.57214374],
       [12.63199382, 11.55465583],
       [12.0752837 , 17.95056363],
       [15.30104963, 13.15907309],
       [16.36216086, 12.41916961],
       [18.3943442 , 17.2642281 ],
       [15.72006171, 18.03048879],
       [16.40085232, 13.88905179],
       [11.06535835, 13.27539443]])

In [11]:
i_arr = np.eye(5)
i_arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
emp = np.empty((4,6))
emp

array([[15.45989608, 15.67665242, 17.72543802, 13.79444201, 15.25416777,
        14.91651212],
       [15.5021184 , 19.57214374, 12.63199382, 11.55465583, 12.0752837 ,
        17.95056363],
       [15.30104963, 13.15907309, 16.36216086, 12.41916961, 18.3943442 ,
        17.2642281 ],
       [15.72006171, 18.03048879, 16.40085232, 13.88905179, 11.06535835,
        13.27539443]])